from pydantic import BaseModel, Field, field_validator
from typing import Literal, List, Dict, Any


class GenerateRequest(BaseModel):
    """
    Request model for generating content.
    """
    question: str = Field(..., description="Question for content generation")
    local_llm: bool = Field(False, description="Whether to use a local LLM (default: False)")
    provider: Literal["gemini", "mistral"] = Field("gemini", description="Cloud provider to use when local_llm is False")

    @field_validator("question")
    def validate_question(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("question cannot be empty")
        return value.strip()


class GenerateResponse(BaseModel):
    """
    Response model for content generation (stable schema).
    {
      "originalQuestion": "...",
      "providerUsed": "mistral | gemini | local | unknown",
      "usedLocalLLM": false,
      "answer": "final response text"
    }
    """
    originalQuestion: str = Field(..., description="Original question asked by the user")
    providerUsed: str = Field(..., description="Provider used: mistral | gemini | local | unknown")
    usedLocalLLM: bool = Field(..., description="Whether a local LLM was used")
    answer: str = Field(..., description="Final answer text generated by the provider")

    @field_validator("originalQuestion", "providerUsed", "answer")
    def not_empty(cls, value: str) -> str:
        if not value or (isinstance(value, str) and not value.strip()):
            raise ValueError("field cannot be empty")
        return value.strip()



#Paper = Dict[str, JsonValue]

class IdeaRequest(BaseModel):
    domain: str
    venues: List[str]
    papers: List[Dict[str, Any]]


class IdeaResponse(BaseModel):
    ideas: List[str]